#--------------------------------------------
#
# - To make an infinite queue, remove its 'capacity' # field 
# - If 'randomValues' field is informed,  
# 'randomCount' will be ignored
#
#
#
#
#--------------------------------------------
arrivals: 
   Q1: 2.0

queues: 
   Q1: 
      servers: 1
      arrivalMin: 2.0
      arrivalMax: 4.0
      exitMin: 1.0
      exitMax: 2.0
   Q2: 
      servers: 2
      capacity: 5
      exitMin: 4.0
      exitMax: 8.0
   Q3: 
      servers: 2
      capacity: 10
      exitMin: 5.0
      exitMax: 15.0

network: 
-  origin: Q1
   destination: Q2
   probability: 0.8
-  origin: Q1
   destination: Q3
   probability: 0.2
-  origin: Q2
   destination: Q1
   probability: 0.3
-  origin: Q2
   destination: Q2
   probability: 0.5
-  origin: Q3
   destination: Q3
   probability: 0.7

randomCount: 100000
# randomValues: 
# - 0.3
# - 0.4
# - 0.1
# - 0.9
# - 0.9
# - 0.1
# - 0.3
# - 0.4
# - 0.1
# - 0.9
# - 0.9
# - 0.1
# - 0.3
# - 0.4
# - 0.1
# - 0.9
# - 0.9
# - 0.1
# - 0.3
# - 0.4
# - 0.1
# - 0.9
# - 0.9
# - 0.1
# - 0.3
# - 0.4
# - 0.1
# - 0.9
# - 0.9
# - 0.1
# - 0.3
# - 0.4
# - 0.1
# - 0.9
# - 0.9
# - 0.1
# - 0.3
# - 0.4
# - 0.1
# - 0.9
# - 0.9
# - 0.1
# - 0.3
# - 0.4
# - 0.1
# - 0.9
# - 0.9
# - 0.1